#' Report results of conditioning data
#'
#' @description Report results of data analyses run with the \code{csCompare}.
#' @param csCompareObj a list or data frame returned from
#' the \code{csCompare} function.
#' @param csSensitivityObj Sensitivity analysis results returned from the
#' \code{csSensitivity} function
#' @param save If argument is set to \code{TRUE} (default), the results are
#' saved as a .txt file. If set to \code{FALSE} the results are printed on
#' screen.
#' @param fileName The file name of the produced report. The argument is
#' ignored if \code{save} is set to \code{FALSE}.
#' @examples
#' tmp <- csCompare(cs1 = c(1, 2, 3, 1, 4), cs2 = c(10, 12, 12, 31, 13))
#' csReport(tmp)
#' @export
csReport <- function(csCompareObj = NULL, csSensitivityObj = NULL, save = TRUE,
                      fileName = "report"){

    if (base::is.null(csCompareObj) && base::is.null(csSensitivityObj)){
      rep <- "[No report was produced.]"
    }

    if (!base::is.null(csCompareObj)){
      # Check whether the csCompareObj has been generated by
      # the csCompare function.
      if (!base::is.list(csCompareObj)){
        stop("The csCompareObj has not been generated
             with the csCompare function.")
      } else {

      # Report frequentist results
      repF <- paste0("We perfromed a ",
                    csCompareObj$freq.results[["alternative"]],
                    csCompareObj$freq.results[["method"]],
                    ". The results of the t-test are t (",
                    csCompareObj$freq.results[["df"]],
                    ") = ",
                    base::round(as.numeric(as.character(csCompareObj$freq.results[["t.statistic"]])), 3),
                    ", p = ",
                    base::round(as.numeric(as.character(csCompareObj$freq.results[["p.value"]])), 3),
                    ".")

      # Report Bayesian results
      repB <- paste0("We perfromed a ",
                    csCompareObj$freq.results[["alternative"]],
                    "Bayesian t-test, with a Catchy prior, with its width set to ",
                    csCompareObj$bayes.results[["rscale"]],
                    ". The BF10 was equal to BF10 = ",
                    csCompareObj$bayes.results[["bf10"]],
                    ". The BF01 was equal to BF01 = ",
                    csCompareObj$bayes.results[["bf01"]],
                    ".")
      }
      rep <- paste(repF, repB, collapse = " ")
    }

  if (!base::is.null(csSensitivityObj)){
    # Check whether the csSensitivityObj has been generated by
    # the csSensitivity function.
    if (!base::is.list(csSensitivityObj)){
      stop("The csSensitivityObj has not been generated
           with the csSensitivity function.")
    } else {
      # Report Sensitivity analysis results
      repB <- paste0("We perfromed a Sensitivity Analysis using the scaling factors: ",
                     paste(csSensitivityObj$rscale, collapse = ", "),
                     ". The results for BF01 were: ",
                     paste(round(as.numeric(
                       as.character(csSensitivityObj$bf01)), 2),
                       collapse = ", "),
                     ". The results for BF10 were: ",
                     paste(round(as.numeric
                                 (as.character(csSensitivityObj$bf10)), 2),
                           collapse = ", "),
                     ".")
    }
    rep <- paste(repF, repB, collapse = " ")
  }
    # Save file if that is asked, otherwise print the results on screen.
    if (save){
      base::cat(rep, file = base::paste0(fileName, ".txt"))
    } else{
      base::cat(rep)
    }
}


